2024-01-17 22:20:01,875:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:01,931:INFO : ....done with record 6438
2024-01-17 22:20:01,931:INFO : ....starting to load record 6461
2024-01-17 22:20:01,931:INFO :     10.17613/M66K17 hc:18327 1000360-11989
2024-01-17 22:20:01,932:INFO :     finding or creating community...
2024-01-17 22:20:01,958:ERROR : url for API request:
2024-01-17 22:20:01,958:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:01,958:ERROR : response status code:
2024-01-17 22:20:01,958:ERROR : 500
2024-01-17 22:20:01,958:ERROR : Internal Server Error
2024-01-17 22:20:01,958:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:01,958:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,017:INFO : ....done with record 6461
2024-01-17 22:20:02,017:INFO : ....starting to load record 6465
2024-01-17 22:20:02,017:INFO :     10.17613/M6PK2Z hc:18335 1000360-11998
2024-01-17 22:20:02,017:INFO :     finding or creating community...
2024-01-17 22:20:02,041:ERROR : url for API request:
2024-01-17 22:20:02,041:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,041:ERROR : response status code:
2024-01-17 22:20:02,041:ERROR : 500
2024-01-17 22:20:02,041:ERROR : Internal Server Error
2024-01-17 22:20:02,041:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,041:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,100:INFO : ....done with record 6465
2024-01-17 22:20:02,100:INFO : ....starting to load record 6471
2024-01-17 22:20:02,100:INFO :     10.17613/M6X287 hc:18347 1000360-12010
2024-01-17 22:20:02,101:INFO :     finding or creating community...
2024-01-17 22:20:02,125:ERROR : url for API request:
2024-01-17 22:20:02,125:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,125:ERROR : response status code:
2024-01-17 22:20:02,125:ERROR : 500
2024-01-17 22:20:02,125:ERROR : Internal Server Error
2024-01-17 22:20:02,126:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,126:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,185:INFO : ....done with record 6471
2024-01-17 22:20:02,185:INFO : ....starting to load record 6472
2024-01-17 22:20:02,185:INFO :     10.17613/M6S869 hc:18349 1000360-12012
2024-01-17 22:20:02,186:INFO :     finding or creating community...
2024-01-17 22:20:02,211:ERROR : url for API request:
2024-01-17 22:20:02,211:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,211:ERROR : response status code:
2024-01-17 22:20:02,211:ERROR : 500
2024-01-17 22:20:02,211:ERROR : Internal Server Error
2024-01-17 22:20:02,211:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,212:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,271:INFO : ....done with record 6472
2024-01-17 22:20:02,271:INFO : ....starting to load record 6477
2024-01-17 22:20:02,271:INFO :     10.17613/M64K20 hc:18359 1000360-12022
2024-01-17 22:20:02,271:INFO :     finding or creating community...
2024-01-17 22:20:02,293:ERROR : url for API request:
2024-01-17 22:20:02,293:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,293:ERROR : response status code:
2024-01-17 22:20:02,293:ERROR : 500
2024-01-17 22:20:02,293:ERROR : Internal Server Error
2024-01-17 22:20:02,293:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,293:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,357:INFO : ....done with record 6477
2024-01-17 22:20:02,357:INFO : ....starting to load record 6486
2024-01-17 22:20:02,357:INFO :     10.17613/M6ZW0S hc:18377 1000360-12070
2024-01-17 22:20:02,357:INFO :     finding or creating community...
2024-01-17 22:20:02,387:ERROR : url for API request:
2024-01-17 22:20:02,388:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,388:ERROR : response status code:
2024-01-17 22:20:02,388:ERROR : 500
2024-01-17 22:20:02,388:ERROR : Internal Server Error
2024-01-17 22:20:02,388:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,388:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,442:INFO : ....done with record 6486
2024-01-17 22:20:02,442:INFO : ....starting to load record 6490
2024-01-17 22:20:02,443:INFO :     10.17613/M6PC2W hc:18387 1000360-12098
2024-01-17 22:20:02,443:INFO :     finding or creating community...
2024-01-17 22:20:02,467:ERROR : url for API request:
2024-01-17 22:20:02,467:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,467:ERROR : response status code:
2024-01-17 22:20:02,467:ERROR : 500
2024-01-17 22:20:02,467:ERROR : Internal Server Error
2024-01-17 22:20:02,467:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,467:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,524:INFO : ....done with record 6490
2024-01-17 22:20:02,524:INFO : ....starting to load record 6502
2024-01-17 22:20:02,524:INFO :     10.17613/M67569 hc:18411 1000360-12215
2024-01-17 22:20:02,525:INFO :     finding or creating community...
2024-01-17 22:20:02,550:ERROR : url for API request:
2024-01-17 22:20:02,550:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,550:ERROR : response status code:
2024-01-17 22:20:02,550:ERROR : 500
2024-01-17 22:20:02,550:ERROR : Internal Server Error
2024-01-17 22:20:02,550:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,550:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,609:INFO : ....done with record 6502
2024-01-17 22:20:02,609:INFO : ....starting to load record 6516
2024-01-17 22:20:02,609:INFO :     10.17613/M6585B hc:18439 1000360-12274
2024-01-17 22:20:02,609:INFO :     finding or creating community...
2024-01-17 22:20:02,637:ERROR : url for API request:
2024-01-17 22:20:02,637:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,637:ERROR : response status code:
2024-01-17 22:20:02,637:ERROR : 500
2024-01-17 22:20:02,637:ERROR : Internal Server Error
2024-01-17 22:20:02,637:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,638:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,694:INFO : ....done with record 6516
2024-01-17 22:20:02,695:INFO : ....starting to load record 6521
2024-01-17 22:20:02,695:INFO :     10.17613/M6GK23 hc:18449 1000360-12289
2024-01-17 22:20:02,695:INFO :     finding or creating community...
2024-01-17 22:20:02,716:ERROR : url for API request:
2024-01-17 22:20:02,716:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,716:ERROR : response status code:
2024-01-17 22:20:02,716:ERROR : 500
2024-01-17 22:20:02,716:ERROR : Internal Server Error
2024-01-17 22:20:02,717:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,717:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,780:INFO : ....done with record 6521
2024-01-17 22:20:02,780:INFO : ....starting to load record 6530
2024-01-17 22:20:02,780:INFO :     10.17613/M69V8K hc:18467 1000360-12314
2024-01-17 22:20:02,781:INFO :     finding or creating community...
2024-01-17 22:20:02,803:ERROR : url for API request:
2024-01-17 22:20:02,803:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,803:ERROR : response status code:
2024-01-17 22:20:02,803:ERROR : 500
2024-01-17 22:20:02,803:ERROR : Internal Server Error
2024-01-17 22:20:02,803:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,803:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,865:INFO : ....done with record 6530
2024-01-17 22:20:02,865:INFO : ....starting to load record 6537
2024-01-17 22:20:02,865:INFO :     10.17613/M6DK13 hc:18481 1000360-12367
2024-01-17 22:20:02,865:INFO :     finding or creating community...
2024-01-17 22:20:02,891:ERROR : url for API request:
2024-01-17 22:20:02,891:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,891:ERROR : response status code:
2024-01-17 22:20:02,891:ERROR : 500
2024-01-17 22:20:02,891:ERROR : Internal Server Error
2024-01-17 22:20:02,892:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,892:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:02,951:INFO : ....done with record 6537
2024-01-17 22:20:02,951:INFO : ....starting to load record 6538
2024-01-17 22:20:02,951:INFO :     10.17613/M65271 hc:18483 1000360-12375
2024-01-17 22:20:02,951:INFO :     finding or creating community...
2024-01-17 22:20:02,980:ERROR : url for API request:
2024-01-17 22:20:02,980:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:02,980:ERROR : response status code:
2024-01-17 22:20:02,980:ERROR : 500
2024-01-17 22:20:02,980:ERROR : Internal Server Error
2024-01-17 22:20:02,980:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:02,980:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,036:INFO : ....done with record 6538
2024-01-17 22:20:03,036:INFO : ....starting to load record 6539
2024-01-17 22:20:03,036:INFO :     10.17613/M61C54 hc:18485 1000360-12378
2024-01-17 22:20:03,037:INFO :     finding or creating community...
2024-01-17 22:20:03,065:ERROR : url for API request:
2024-01-17 22:20:03,065:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,065:ERROR : response status code:
2024-01-17 22:20:03,065:ERROR : 500
2024-01-17 22:20:03,065:ERROR : Internal Server Error
2024-01-17 22:20:03,065:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,066:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,122:INFO : ....done with record 6539
2024-01-17 22:20:03,122:INFO : ....starting to load record 6541
2024-01-17 22:20:03,122:INFO :     10.17613/M6RV90 hc:18489 1000360-12388
2024-01-17 22:20:03,123:INFO :     finding or creating community...
2024-01-17 22:20:03,149:ERROR : url for API request:
2024-01-17 22:20:03,149:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,149:ERROR : response status code:
2024-01-17 22:20:03,149:ERROR : 500
2024-01-17 22:20:03,149:ERROR : Internal Server Error
2024-01-17 22:20:03,149:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,150:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,208:INFO : ....done with record 6541
2024-01-17 22:20:03,208:INFO : ....starting to load record 6548
2024-01-17 22:20:03,208:INFO :     10.17613/M6VP15 hc:18503 1000360-12419
2024-01-17 22:20:03,208:INFO :     finding or creating community...
2024-01-17 22:20:03,229:ERROR : url for API request:
2024-01-17 22:20:03,230:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,230:ERROR : response status code:
2024-01-17 22:20:03,230:ERROR : 500
2024-01-17 22:20:03,230:ERROR : Internal Server Error
2024-01-17 22:20:03,230:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,230:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,293:INFO : ....done with record 6548
2024-01-17 22:20:03,293:INFO : ....starting to load record 6552
2024-01-17 22:20:03,294:INFO :     10.17613/M6BP04 hc:18511 1000360-12430
2024-01-17 22:20:03,294:INFO :     finding or creating community...
2024-01-17 22:20:03,315:ERROR : url for API request:
2024-01-17 22:20:03,315:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,315:ERROR : response status code:
2024-01-17 22:20:03,315:ERROR : 500
2024-01-17 22:20:03,315:ERROR : Internal Server Error
2024-01-17 22:20:03,316:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,316:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,379:INFO : ....done with record 6552
2024-01-17 22:20:03,379:INFO : ....starting to load record 6567
2024-01-17 22:20:03,379:INFO :     10.17613/M60865 hc:18555 1000360-12493
2024-01-17 22:20:03,380:INFO :     finding or creating community...
2024-01-17 22:20:03,403:ERROR : url for API request:
2024-01-17 22:20:03,403:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,403:ERROR : response status code:
2024-01-17 22:20:03,403:ERROR : 500
2024-01-17 22:20:03,403:ERROR : Internal Server Error
2024-01-17 22:20:03,404:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,404:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,464:INFO : ....done with record 6567
2024-01-17 22:20:03,465:INFO : ....starting to load record 6583
2024-01-17 22:20:03,465:INFO :     10.17613/M6HZ9V hc:18589 1000360-12560
2024-01-17 22:20:03,465:INFO :     finding or creating community...
2024-01-17 22:20:03,483:ERROR : url for API request:
2024-01-17 22:20:03,483:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,483:ERROR : response status code:
2024-01-17 22:20:03,483:ERROR : 500
2024-01-17 22:20:03,483:ERROR : Internal Server Error
2024-01-17 22:20:03,483:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,483:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,547:INFO : ....done with record 6583
2024-01-17 22:20:03,547:INFO : ....starting to load record 6596
2024-01-17 22:20:03,547:INFO :     10.17613/M6Z576 hc:18629 1000360-12618
2024-01-17 22:20:03,547:INFO :     finding or creating community...
2024-01-17 22:20:03,579:ERROR : url for API request:
2024-01-17 22:20:03,579:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,579:ERROR : response status code:
2024-01-17 22:20:03,579:ERROR : 500
2024-01-17 22:20:03,579:ERROR : Internal Server Error
2024-01-17 22:20:03,579:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,579:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,628:INFO : ....done with record 6596
2024-01-17 22:20:03,629:INFO : ....starting to load record 6600
2024-01-17 22:20:03,629:INFO :     10.17613/M6F298 hc:18637 1000360-12626
2024-01-17 22:20:03,629:INFO :     finding or creating community...
2024-01-17 22:20:03,643:ERROR : url for API request:
2024-01-17 22:20:03,643:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,643:ERROR : response status code:
2024-01-17 22:20:03,643:ERROR : 500
2024-01-17 22:20:03,643:ERROR : Internal Server Error
2024-01-17 22:20:03,644:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,644:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,714:INFO : ....done with record 6600
2024-01-17 22:20:03,714:INFO : ....starting to load record 6614
2024-01-17 22:20:03,714:INFO :     10.17613/M6QC5B hc:18675 1000360-12686
2024-01-17 22:20:03,715:INFO :     finding or creating community...
2024-01-17 22:20:03,730:ERROR : url for API request:
2024-01-17 22:20:03,730:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,730:ERROR : response status code:
2024-01-17 22:20:03,730:ERROR : 500
2024-01-17 22:20:03,730:ERROR : Internal Server Error
2024-01-17 22:20:03,730:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,730:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,798:INFO : ....done with record 6614
2024-01-17 22:20:03,799:INFO : ....starting to load record 6615
2024-01-17 22:20:03,799:INFO :     10.17613/M6KP1P hc:18677 1000360-12688
2024-01-17 22:20:03,799:INFO :     finding or creating community...
2024-01-17 22:20:03,824:ERROR : url for API request:
2024-01-17 22:20:03,824:ERROR : https://localhost/api/communities/hcommons
2024-01-17 22:20:03,824:ERROR : response status code:
2024-01-17 22:20:03,824:ERROR : 500
2024-01-17 22:20:03,824:ERROR : Internal Server Error
2024-01-17 22:20:03,824:ERROR : ERROR: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons
2024-01-17 22:20:03,824:ERROR : ERROR: ['Traceback (most recent call last):\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads\n    return _default_decoder.decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode\n    obj, end = self.raw_decode(s)\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n', 'simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 92, in api_request\n    json_response = response.json() if method != "DELETE" else None\n', '  File "/Users/ianscott/.local/share/virtualenvs/knowledge-commons-repository-WoFj9yE6/lib/python3.9/site-packages/requests/models.py", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n', 'requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 1402, in load_records_into_invenio\n    result = create_full_invenio_record(rec, no_updates)\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 895, in create_full_invenio_record\n    community_check = api_request(\n', '  File "/Users/ianscott/Development/knowledge-commons-repository/scripts/core-migrate/core_migrate/record_loader.py", line 109, in api_request\n    raise requests.HTTPError(\n', 'requests.exceptions.HTTPError: Failed to decode JSON response from API request to https://localhost/api/communities/hcommons\n']
2024-01-17 22:20:03,883:INFO : ....done with record 6615
2024-01-17 22:20:03,884:INFO : ....starting to load record 6621
2024-01-17 22:20:03,884:INFO :     10.17613/M6T857 hc:18689 1000360-12719
2024-01-17 22:20:03,884:INFO :     finding or creating community...
